/-!
# MemStorageCore — Model and Proofs for `MemStorageCore` log operations

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

This file provides a formal model of the pure log-management operations of `MemStorageCore`
(`src/storage.rs`), and proves key correctness properties about `firstIndex`, `lastIndex`,
`compact`, and `append`.

## Background

`MemStorageCore` maintains an in-memory Raft log with two regions:
1. A **snapshot** region: entries up to `snapshot_metadata.index` have been compacted.
2. An **entries** region: a contiguous slice of `Entry` values with indices
   `[firstIndex, lastIndex]`.

The key invariants (Raft §7):
* Entries are **contiguous**: `entries[i].index = firstIndex + i` for all `i`.
* `firstIndex ≤ lastIndex + 1` (with equality meaning the slice is empty).
* `compact` advances `firstIndex` (never decreases it) and never changes `lastIndex`.
* `append` may truncate and extend from any valid position ≥ `firstIndex`.

## Model

We abstract the Rust implementation to a pure functional structure:

```
MemStorageCore.snapshotIndex : Nat   -- last compacted index (= firstIndex - 1 always)
MemStorageCore.terms         : List Nat  -- terms[i] is the term of entry at (snapshotIndex + 1 + i)
```

By construction, `firstIndex = snapshotIndex + 1` and `lastIndex = snapshotIndex + terms.length`,
so the contiguity invariant is baked in and requires no separate proof.

**Abstractions / omissions**:
- Entry payloads omitted (only terms are modelled, not data).
- `u64` → `Nat`; no overflow.
- Snapshot content (conf_state, data) omitted; only the index is tracked.
- Error paths (`compact_index > lastIndex + 1`, `ents[0].index < firstIndex`) not modelled.
  Specs cover the success path.
- `apply_snapshot` is not modelled here.

Source: `src/storage.rs` (`MemStorageCore`)

🔬 Generated by Lean Squad automated formal verification.
-/

namespace FVSquad.MemStorage

-- ═══════════════════════════════════════════════════════════
-- Data structure
-- ═══════════════════════════════════════════════════════════

/-- Pure functional model of `MemStorageCore`'s log region.

    `snapshotIndex` records the last compacted log index (entries at indices ≤ snapshotIndex
    have been discarded).  Entry at position `i` (0-based) in `terms` has log index
    `snapshotIndex + 1 + i`.  This encoding makes the contiguity invariant definitionally true.

    Corresponds to the `entries` + `snapshot_metadata.index` fields of `MemStorageCore`
    in `src/storage.rs`. -/
structure MemStorageCore where
  /-- Last compacted log index.  Entries with index ≤ snapshotIndex are gone. -/
  snapshotIndex : Nat
  /-- Terms of the retained entries.  `terms[i]` is the term of entry at index
      `snapshotIndex + 1 + i`. -/
  terms : List Nat
  deriving Repr, DecidableEq

-- ═══════════════════════════════════════════════════════════
-- Core definitions (models of `first_index` / `last_index`)
-- ═══════════════════════════════════════════════════════════

/-- Index of the first retained entry.
    When `terms` is empty, this is `snapshotIndex + 1` (sentinel: the slot *after* the
    snapshot, consistent with the Rust `first_index` returning `snapshot_metadata.index + 1`
    when `entries` is empty).
    Models `MemStorageCore::first_index` in `src/storage.rs`. -/
def firstIndex (s : MemStorageCore) : Nat := s.snapshotIndex + 1

/-- Index of the last retained entry.
    When `terms` is empty, this equals `snapshotIndex` (= firstIndex - 1), so
    `firstIndex s = lastIndex s + 1` for an empty log.
    Models `MemStorageCore::last_index` in `src/storage.rs`. -/
def lastIndex (s : MemStorageCore) : Nat := s.snapshotIndex + s.terms.length

/-- Number of retained entries. -/
def entryCount (s : MemStorageCore) : Nat := s.terms.length

-- ═══════════════════════════════════════════════════════════
-- `compact` — discard entries before `compactIndex`
-- ═══════════════════════════════════════════════════════════

/-- Compact the log up to (exclusive) `compactIndex`.
    Entries with index < `compactIndex` are discarded.

    * If `compactIndex ≤ firstIndex s`, this is a no-op.
    * Otherwise, `dropCount = compactIndex - firstIndex s` entries are removed from the front.

    Models `MemStorageCore::compact` in `src/storage.rs` (success path only;
    the panic for `compactIndex > lastIndex + 1` is not modelled). -/
def compact (s : MemStorageCore) (compactIndex : Nat) : MemStorageCore :=
  if compactIndex ≤ firstIndex s then s
  else
    let dropCount := compactIndex - firstIndex s
    { snapshotIndex := compactIndex - 1
      terms := s.terms.drop dropCount }

-- ═══════════════════════════════════════════════════════════
-- `append` — truncate-and-extend
-- ═══════════════════════════════════════════════════════════

/-- Append (truncate-and-extend) a list of new terms starting at log index `startIndex`.
    Entries at indices ≥ `startIndex` are replaced by `newTerms`.

    Preconditions (not checked; panic/error paths elided):
    * `startIndex ≥ firstIndex s`  (no overwrite of compacted region)
    * `startIndex ≤ lastIndex s + 1`  (no gap)

    Models `MemStorageCore::append` in `src/storage.rs`. -/
def append (s : MemStorageCore) (startIndex : Nat) (newTerms : List Nat) : MemStorageCore :=
  if newTerms.isEmpty then s
  else
    let keepCount := startIndex - firstIndex s
    { s with terms := s.terms.take keepCount ++ newTerms }

-- ═══════════════════════════════════════════════════════════
-- Helper lemmas
-- ═══════════════════════════════════════════════════════════

private theorem terms_length_zero_iff (s : MemStorageCore) :
    s.terms.length = 0 ↔ s.terms = [] := by
  exact List.eq_nil_iff_length_eq_zero.symm

-- ═══════════════════════════════════════════════════════════
-- Theorems
-- ═══════════════════════════════════════════════════════════

/-! ### MS1 — `firstIndex ≤ lastIndex + 1` (always)

The half-open interval `[firstIndex, lastIndex]` is always well-formed. -/

/-- `firstIndex s ≤ lastIndex s + 1` for every `s`.

    Proof: `firstIndex s = snapshotIndex + 1` and `lastIndex s = snapshotIndex + terms.length`,
    so `lastIndex s + 1 = snapshotIndex + terms.length + 1 ≥ snapshotIndex + 1 = firstIndex s`. -/
theorem MS1_firstIndex_le_lastIndex_succ (s : MemStorageCore) :
    firstIndex s ≤ lastIndex s + 1 := by
  simp only [firstIndex, lastIndex]
  omega

/-! ### MS2 — Empty iff `lastIndex < firstIndex`

The entries region is empty iff `lastIndex s < firstIndex s`. -/

/-- `terms` is empty iff `lastIndex s < firstIndex s`. -/
theorem MS2_empty_iff_lastIndex_lt (s : MemStorageCore) :
    s.terms = [] ↔ lastIndex s < firstIndex s := by
  rw [← terms_length_zero_iff]
  simp only [firstIndex, lastIndex]
  omega

/-! ### MS3 — `compact` is a no-op when `compactIndex ≤ firstIndex` -/

/-- If `compactIndex ≤ firstIndex s`, `compact` returns `s` unchanged. -/
theorem MS3_compact_noop (s : MemStorageCore) (compactIndex : Nat)
    (h : compactIndex ≤ firstIndex s) :
    compact s compactIndex = s := by
  simp only [compact, firstIndex] at *
  simp only [h, ↓reduceIte]

/-! ### MS4 — `compact` preserves `lastIndex` -/

/-- `lastIndex` is unchanged by `compact` (assuming `compactIndex ≤ lastIndex s + 1`).

    The terms dropped from the front had indices in `[firstIndex, compactIndex)`.
    The new `snapshotIndex = compactIndex - 1`, and the remaining terms length =
    `terms.length - dropCount`, so `lastIndex = (compactIndex - 1) + (terms.length - dropCount) =
    snapshotIndex + terms.length = lastIndex s`. -/
theorem MS4_compact_preserves_lastIndex (s : MemStorageCore) (compactIndex : Nat)
    (h : compactIndex ≤ lastIndex s + 1) :
    lastIndex (compact s compactIndex) = lastIndex s := by
  simp only [compact, lastIndex, firstIndex] at *
  by_cases hle : compactIndex ≤ s.snapshotIndex + 1
  · simp only [hle, ↓reduceIte]
  · simp only [hle, ↓reduceIte]
    have hlen : compactIndex - (s.snapshotIndex + 1) ≤ s.terms.length := by omega
    rw [List.length_drop]
    omega

/-! ### MS5 — `compact` advances `firstIndex` to `compactIndex` -/

/-- After compact, `firstIndex = max (firstIndex s) compactIndex`. -/
theorem MS5_compact_firstIndex (s : MemStorageCore) (compactIndex : Nat) :
    firstIndex (compact s compactIndex) = max (firstIndex s) compactIndex := by
  simp only [compact, firstIndex]
  by_cases hle : compactIndex ≤ s.snapshotIndex + 1
  · simp only [hle, ↓reduceIte]; omega
  · simp only [hle, ↓reduceIte]; omega

/-! ### MS6 — `append` preserves `firstIndex` -/

/-- `append` does not change `firstIndex` (the snapshotIndex is unchanged). -/
theorem MS6_append_preserves_firstIndex (s : MemStorageCore) (startIndex : Nat)
    (newTerms : List Nat) :
    firstIndex (append s startIndex newTerms) = firstIndex s := by
  simp only [append, firstIndex]
  by_cases hne : newTerms = []
  · simp [hne]
  · have : newTerms.isEmpty = false := List.isEmpty_eq_false_iff.mpr hne
    simp [this]

/-! ### MS7 — `lastIndex` after non-empty `append` -/

/-- After appending `newTerms` (non-empty) starting at `startIndex`,
    `lastIndex = startIndex + newTerms.length - 1`.

    Preconditions:
    * `startIndex ≥ firstIndex s` (no overwrite of compacted region)
    * `startIndex ≤ lastIndex s + 1` (no gap) -/
theorem MS7_append_lastIndex (s : MemStorageCore) (startIndex : Nat) (newTerms : List Nat)
    (hne : newTerms ≠ [])
    (hge : startIndex ≥ firstIndex s)
    (hle : startIndex ≤ lastIndex s + 1) :
    lastIndex (append s startIndex newTerms) = startIndex + newTerms.length - 1 := by
  -- Case split on newTerms form to reduce isEmpty
  rcases newTerms with (_ | ⟨hd, tl⟩)
  · exact absurd rfl hne
  · simp only [append, List.isEmpty, Bool.false_eq_true, ↓reduceIte, lastIndex, firstIndex] at *
    rw [List.length_append, List.length_take]
    have hmin : min (startIndex - (s.snapshotIndex + 1)) s.terms.length =
                startIndex - (s.snapshotIndex + 1) := by
      apply Nat.min_eq_left; omega
    rw [hmin]; simp; omega

/-! ### MS8 — `append []` is a no-op -/

/-- Appending an empty list is a no-op. -/
theorem MS8_append_empty_noop (s : MemStorageCore) (startIndex : Nat) :
    append s startIndex [] = s := by
  simp [append]

end FVSquad.MemStorage
