import FVSquad.ProgressTracker

/-!
# ProgressTrackerCorrespondence — Lean 4 Correspondence Tests

> 🔬 *Lean Squad — automated formal verification for `dsyme/raft-lean-squad`.*

Runtime correspondence tests (`#guard`) that verify the Lean model of
`ProgressTracker` agrees with the expected output of the Rust implementation
on representative inputs.

Source: `src/tracker.rs` (`apply_conf`, `ProgressTracker`)
Lean model: `FVSquad/ProgressTracker.lean`

## Methodology

Each `#guard` test encodes a concrete operation on the Lean progress-map model
and asserts the expected structural result drawn from the Rust implementation's
behaviour on the same inputs.  `#guard` is evaluated at compile time.

## Test fixtures

Tests cover:
- `removePeer`: peer absent / peer present (reduces map size)
- `insertPeer`: fresh insert / replace existing
- `updatePeer`: no-op when id absent / applies function when present
- `applyChange Add` / `applyChange Remove`: single-change semantics
- `applyChanges`: multi-step sequence, order correctness
- `initTracker`: fresh initialization, wf of all peers
- Invariant checks: `all_wf` holds after each operation

Correspondence level: **abstraction** — the Lean model uses an association list
instead of a HashMap; key uniqueness is not enforced by the model but `insertPeer`
logically replaces existing entries by removing them first.

> 🔬 Generated by Lean Squad automated formal verification (Run 97).
-/

open FVSquad.ProgressTracker FVSquad.Progress

namespace FVSquad.ProgressTrackerCorrespondence

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

/-- A well-formed Progress in Replicate state: matched=5, next_idx=6. -/
private def pRep : Progress :=
  { matched := 5, next_idx := 6, state := ProgressState.Replicate,
    paused := false, pending_snapshot := 0, pending_request_snapshot := 0,
    recent_active := true, ins_full := false }

/-- A well-formed Progress in Probe state: matched=2, next_idx=7. -/
private def pProbe : Progress :=
  { matched := 2, next_idx := 7, state := ProgressState.Probe,
    paused := false, pending_snapshot := 0, pending_request_snapshot := 0,
    recent_active := true, ins_full := false }

/-- A sample three-peer progress map: peers 1, 2, 3. -/
private def pm3 : ProgressMap :=
  [(1, pRep), (2, pProbe), (3, pRep)]

instance : BEq Progress where
  beq a b :=
    a.matched == b.matched &&
    a.next_idx == b.next_idx &&
    a.state == b.state &&
    a.paused == b.paused &&
    a.pending_snapshot == b.pending_snapshot &&
    a.pending_request_snapshot == b.pending_request_snapshot &&
    a.recent_active == b.recent_active &&
    a.ins_full == b.ins_full

-- ---------------------------------------------------------------------------
-- removePeer tests
-- ---------------------------------------------------------------------------

-- 1. Removing a peer that is present reduces size by 1.
#guard (removePeer pm3 2).length == 2

-- 2. Removing a peer that is absent leaves size unchanged.
#guard (removePeer pm3 99).length == 3

-- 3. Removed peer is no longer in the map.
#guard !(removePeer pm3 1).any (fun p => p.1 == 1)

-- 4. Other peers remain after removal.
#guard (removePeer pm3 1).any (fun p => p.1 == 2)
#guard (removePeer pm3 1).any (fun p => p.1 == 3)

-- 5. Removing from empty map yields empty map.
#guard (removePeer [] 5 : ProgressMap).length == 0

-- ---------------------------------------------------------------------------
-- insertPeer tests
-- ---------------------------------------------------------------------------

-- 6. Inserting a new peer increases size by 1.
#guard (insertPeer pm3 10 pRep).length == 4

-- 7. Inserting an existing peer does NOT duplicate (replaces).
#guard (insertPeer pm3 1 pProbe).length == 3

-- 8. After inserting peer 10, it is present.
#guard (insertPeer pm3 10 pRep).any (fun p => p.1 == 10)

-- 9. The new peer carries the supplied Progress value.
#guard ((insertPeer pm3 10 pRep).find? (fun p => p.1 == 10)).map (·.2) == some pRep

-- 10. Replacing peer 1 gives it the new Progress.
#guard ((insertPeer pm3 1 pProbe).find? (fun p => p.1 == 1)).map (·.2) == some pProbe

-- ---------------------------------------------------------------------------
-- updatePeer tests
-- ---------------------------------------------------------------------------

-- 11. Updating peer 2 (present): function is applied.
#guard ((updatePeer pm3 2 (fun p => { p with matched := 99 })).find?
    (fun e => e.1 == 2)).map (·.2.matched) == some 99

-- 12. Other peers are unchanged by updatePeer.
#guard ((updatePeer pm3 2 (fun p => { p with matched := 99 })).find?
    (fun e => e.1 == 1)).map (·.2.matched) == some 5

-- 13. Updating a peer not in the map leaves size unchanged.
#guard (updatePeer pm3 99 (fun p => { p with matched := 1 })).length == 3

-- ---------------------------------------------------------------------------
-- applyChange tests
-- ---------------------------------------------------------------------------

-- 14. Add a new peer (id=7, next_idx=10): map grows by 1.
#guard (applyChange pm3 7 ChangeType.Add 10).length == 4

-- 15. Newly added peer uses Progress.mk_new semantics: matched=0.
#guard ((applyChange pm3 7 ChangeType.Add 10).find? (fun e => e.1 == 7)).map
    (·.2.matched) == some 0

-- 16. Newly added peer has next_idx = supplied next_idx.
#guard ((applyChange pm3 7 ChangeType.Add 10).find? (fun e => e.1 == 7)).map
    (·.2.next_idx) == some 10

-- 17. Remove an existing peer via applyChange.
#guard (applyChange pm3 2 ChangeType.Remove 10).length == 2

-- 18. Removed peer is absent after applyChange Remove.
#guard !(applyChange pm3 2 ChangeType.Remove 10).any (fun e => e.1 == 2)

-- 19. applyChange Remove on absent peer leaves size unchanged.
#guard (applyChange pm3 99 ChangeType.Remove 10).length == 3

-- ---------------------------------------------------------------------------
-- applyChanges tests
-- ---------------------------------------------------------------------------

-- 20. Empty changes list: map unchanged.
#guard (applyChanges pm3 [] 5).length == 3

-- 21. Add then Remove same id: map unchanged in size.
#guard (applyChanges pm3 [(7, ChangeType.Add), (7, ChangeType.Remove)] 10).length == 3

-- 22. Remove then Add same id: peer re-appears with fresh Progress.
#guard (applyChanges pm3 [(2, ChangeType.Remove), (2, ChangeType.Add)] 10).any
    (fun e => e.1 == 2)

-- 23. Sequencing two Adds for distinct peers: map grows by 2.
#guard (applyChanges pm3 [(7, ChangeType.Add), (8, ChangeType.Add)] 10).length == 5

-- ---------------------------------------------------------------------------
-- initTracker tests
-- ---------------------------------------------------------------------------

-- 24. initTracker with 3 ids yields 3 entries.
#guard (initTracker [1, 2, 3] 5).length == 3

-- 25. Each peer in initTracker has the supplied next_idx.
#guard (initTracker [1, 2, 3] 5).all (fun e => e.2.next_idx == 5)

-- 26. Each peer in initTracker has matched=0 (models Progress::new).
#guard (initTracker [1, 2, 3] 5).all (fun e => e.2.matched == 0)

-- 27. initTracker on empty list yields empty map.
#guard (initTracker [] 5 : ProgressMap).length == 0

-- ---------------------------------------------------------------------------
-- all_wf invariant checks (compile-time)
-- ---------------------------------------------------------------------------

-- 28. pm3 is well-formed: both pRep (5 < 6) and pProbe (2 < 7) satisfy wf.
#guard pm3.all (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- 29. After removePeer, remaining peers still pass wf check.
#guard (removePeer pm3 1).all (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- 30. After insertPeer with mk_new (matched=0, next_idx=8), result is wf.
#guard (insertPeer pm3 10 (Progress.mk_new 8)).all
    (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- 31. After applyChange Add with next_idx=1 (minimum valid), result is wf.
#guard (applyChange pm3 7 ChangeType.Add 1).all
    (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- 32. After applyChanges sequence, all peers pass wf check.
#guard (applyChanges pm3 [(2, ChangeType.Remove), (9, ChangeType.Add)] 3).all
    (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- 33. initTracker result is fully wf (matched=0, next_idx=next_idx ≥ 1).
#guard (initTracker [1, 2, 3, 4] 5).all (fun e => Nat.ble (e.2.matched + 1) e.2.next_idx)

-- ---------------------------------------------------------------------------
-- PT25 / PT26 integration: initTracker + applyChanges membership
-- (Lean Squad Run 116 — Task 5 integration theorems)
-- ---------------------------------------------------------------------------

-- 34. PT25 scenario: peer 1 is in initTracker, not mentioned in changes → still present.
#guard hasPeer (applyChanges (initTracker [1, 2, 3] 5)
    [(4, ChangeType.Add), (2, ChangeType.Remove)] 8) 1 = true

-- 35. PT25 scenario: peer 3 survives a change list that touches only peers 2 and 4.
#guard hasPeer (applyChanges (initTracker [1, 2, 3] 5)
    [(2, ChangeType.Remove), (4, ChangeType.Add)] 8) 3 = true

-- 36. PT25 complement: peer 2 is removed → no longer present.
#guard hasPeer (applyChanges (initTracker [1, 2, 3] 5)
    [(2, ChangeType.Remove)] 8) 2 = false

-- 37. PT26 scenario: peer 9 is added, then unrelated changes → peer 9 is present.
#guard hasPeer (applyChanges (applyChange pm3 9 ChangeType.Add 10)
    [(7, ChangeType.Add), (8, ChangeType.Add)] 10) 9 = true

-- 38. PT26 complement: peer 9 added then removed → no longer present.
#guard hasPeer (applyChanges (applyChange pm3 9 ChangeType.Add 10)
    [(7, ChangeType.Add), (9, ChangeType.Remove)] 10) 9 = false

-- 39. Combined: initTracker + multi-change: peers [1,3] remain; 2 removed; 5 added.
#guard
  let pm' := applyChanges (initTracker [1, 2, 3] 5)
      [(2, ChangeType.Remove), (5, ChangeType.Add)] 10
  hasPeer pm' 1 = true ∧ hasPeer pm' 2 = false ∧
  hasPeer pm' 3 = true ∧ hasPeer pm' 5 = true

-- 40. applyChanges on empty initTracker with one Add creates a single-peer map.
#guard hasPeer (applyChanges (initTracker [] 5) [(7, ChangeType.Add)] 5) 7 = true

-- 41. applyChanges Add then Remove same peer on initTracker leaves it absent.
#guard hasPeer (applyChanges (initTracker [1, 2] 5)
    [(3, ChangeType.Add), (3, ChangeType.Remove)] 5) 3 = false

-- 42. applyChanges Remove then Add same peer restores it with fresh Progress.
#guard hasPeer (applyChanges (initTracker [1, 2] 5)
    [(1, ChangeType.Remove), (1, ChangeType.Add)] 10) 1 = true

-- 43. After Remove-then-Add, the re-added peer has next_idx from applyChanges call.
#guard (applyChanges (initTracker [1, 2] 5)
    [(1, ChangeType.Remove), (1, ChangeType.Add)] 10).any
    (fun e => e.1 == 1 && e.2.next_idx == 10)

end FVSquad.ProgressTrackerCorrespondence
